name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
#   # -------------------------------------------------------------
#   # JOB 1: Test (Commented out for now until you write tests)
#   # -------------------------------------------------------------
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Install Packages
#         run: npm ci
#       - name: Run Tests
#         run: npm run test

  deploy:
    # needs: test #waits for test job to complete before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3 #copy file from github to EC2, run script, and reload the server
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
            cd ~/plovdev-server
            git pull origin main
            npm ci --only=production
            npm run migrate
            pm2 reload plovdev-backend --update-env || pm2 start server.js --name "plovdev-backend"
            pm2 save
            echo "✅ Deployment completed!"